# Custom values for bookstore-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: depauna/book-store
  tag: latest
  pullPolicy: Always

maxSurge: 50%
maxUnavailable: 50%
minReadySeconds: 5

service:
  type: NodePort
  port: 3000
  nodePort: 31444

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
  - chart-example.local
  tls: []

resources:
  requests:
    memory: 500Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
