# Custom values for bookstore-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: depauna/book-store
  tag: user1
  pullPolicy: Always

maxSurge: 50%
maxUnavailable: 50%
minReadySeconds: 5

service:
  type: ClusterIP
  internalPort: 3000
  externalPort: 3000

ingress:
  enabled: true
  annotations: {}
  path: /user1
  hosts:
  - chart-example.local
  tls: []

resources:
  requests:
    memory: 500Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
