# Custom values for bookstore-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

userName: userx

image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

maxSurge: 50%
maxUnavailable: 50%
minReadySeconds: 5

service:
  type: ClusterIP
  internalPort: 27017
  externalPort: 27017

ingress:
  enabled: false
  annotations: {}
  path: /
  hosts:
  - chart-example.local
  tls: []

resources:
  requests:
    memory: 500Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m

nodeSelector: {}

tolerations: []

affinity: {}
