FROM jenkinsci/jenkins:latest

USER root
RUN wget https://storage.googleapis.com/kubernetes-helm/helm-v2.7.2-linux-amd64.tar.gz && \
tar -zxvf helm-v2.7.2-linux-amd64.tar.gz && \
cp linux-amd64/helm /usr/bin/helm && \

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
chmod +x ./kubectl && \
mv ./kubectl /usr/local/bin/kubectl && \

curl -fsSL https://clis.ng.bluemix.net/install/linux | sh && \

wget https://github.com/depauna/meetup-resources/raw/master/meetup-resources/icp-linux-amd64 && \
bx plugin install -f icp-linux-amd64 && \

apt-get update && \
apt-get install docker && \
apt --fix-broken install

RUN /usr/local/bin/install-plugins.sh blueocean-git-pipeline