apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "bookstore-app.fullname" . }}
  labels:
    app: {{ template "bookstore-app.name" . }}
    chart: {{ template "bookstore-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.maxSurge }}
      maxUnavailable: {{ .Values.maxUnavailable }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      app: {{ template "bookstore-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bookstore-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["/bin/sh", "-c"]
          args: ["npm config set mean-angular6:context $APICONTEXTROOT && npm start"]
          env:
          - name: MONGOHOST
            value: "mongo-mongodb-database-service"
          - name: CONTEXTROOT
            value: "/{{ .Values.userName }}/"
          - name: APICONTEXTROOT
            value: "{{ .Values.userName }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: node
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/{{ .Values.userName }}/api"
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: "/{{ .Values.userName }}"
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
