{{- if .Values.ingress.enabled -}}
{{- $fullName := include "bookstore-app.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "bookstore-app.name" . }}
    chart: {{ template "bookstore-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    nginx.ingress.kubernetes.io/app-root: /
spec:
  rules:
    - host: kubernetes-elb-test-1078957791.eu-west-1.elb.amazonaws.com
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.internalPort }}
{{- end }}